# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RNMusicPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNMusicPlayer
  pod 'React', :path => '../node_modules/react-native' # Add React Native dependency
  pod 'RNMusicPlayer', :path => '.'  # Link to your library
end
